import json, re, pathlib, datetime as dt
S=pathlib.Path("/private/tmp/claude-501/-Users-vadim-PyCharmMiscProject-MOEX/0bf15cd7-145a-4cf7-89b2-1807afeb3bd6/scratchpad")
tables=[]; fresh={}
for ln in (S/"freshness.txt").read_text(encoding="utf-8",errors="replace").splitlines():
    if ln.count("|")>=2 and "ERROR" not in ln: t,c,v=ln.split("|",2); fresh[t]=(c,v[:19])
for ln in (S/"db_tables.txt").read_text(encoding="utf-8",errors="replace").splitlines():
    if ln.count("|")<3 or ln.startswith("SET"): continue
    n,rows,size,cols=ln.split("|",3)
    if n.startswith("_"): continue
    f=fresh.get(n,("",""))
    tables.append({"name":n,"rows":max(int(rows),0),"size":size,"cols":cols.count(":"),"fcol":f[0],"last":f[1]})
for t in tables:
    if t["name"]=="candles" and not t["last"]: t["fcol"]="begin_time"; t["last"]="2026-09-03 (5-мин)"
routers=[]
for ln in (S/"repo_inventory.txt").read_text(encoding="utf-8",errors="replace").splitlines():
    m=re.match(r"^([a-z_]+) \| (\d+) endpoints \| (?:prefix=\"([^\"]*)\")? \| ?(.*)$",ln)
    if m and m.group(1)!="__init__": routers.append({"name":m.group(1),"n":int(m.group(2)),"prefix":m.group(3) or "","desc":m.group(4)[:80]})
today=dt.date(2026,9,3)
DOM=[
 {"title":"Открытый интерес","src":"ISS МосБиржи, Algopack","steps":["oi_5min · каждые 5 мин","oi_aggregate · ежечасно","oi_daily · 19:10","contract_calendar · 19:10","futures_turnover · 19:10"],"tables":["open_interest","futures_contracts","mv_oi_daily_stats","ticker_futures_map","instruments"],"api":["open_interest","stats","chart","instruments"],"pages":["/oi","/embed/:indicator","/methodology/oi"],"note":"цена с задержкой 15 мин по лицензии, ОИ актуальный"},
 {"title":"Свечи, ширина рынка, сезонность","src":"ISS МосБиржи","steps":["candles_spot · каждые 5 мин","candles_futures · каждые 5 мин","breadth_daily · 19:10","dividends_daily · 19:10","index_composition_daily · 19:10"],"tables":["candles","breadth_history","dividends","index_composition","delisted_securities","mv_heatmap_stocks"],"api":["candles","breadth","heatmap","seasonality","repo_volume"],"pages":["/strength","/heatmap","/seasonality","/repo","/methodology/strength","/methodology/heatmap","/methodology/seasonality"],"note":""},
 {"title":"Фонды и сделки фондов","src":"Cbonds REST, справки о СЧА УК (ручной ингест), ISS","steps":["funds_daily · 09:00 и 14:30, догон 18:00 МСК (cron)","fetch_distributions · пн 06:30 (cron)","SCHA · вручную, месячно","freefloat_cap_daily · 19:10"],"tables":["fund_data","funds","fund_holdings_history","fund_holdings","fund_distributions","securities_ref","freefloat_cap"],"api":["funds","fund_trades"],"pages":["/funds","/funds-money","/funds-catalog","/fund-trades","/methodology/funds-money","/methodology/funds-catalog"],"note":"состав фондов только из официальных справок (source=interfax_manual)"},
 {"title":"Индексы","src":"ISS МосБиржи","steps":["indices_daily · 09:00 и 19:10","index_candles_hourly · ежечасно","index_intraday · каждые 5 мин"],"tables":["index_data","indices","imoex_weights"],"api":["funds","stats"],"pages":["/strength","/funds"],"note":"сектор/полн. доходность/FX сеттлятся на ISS после 19:10 → лаг 1 день, не баг"},
 {"title":"Макро и Баффетт","src":"Росстат (ВВП), ЦБ (M2, ключевая), SmartLab (капитализация), ISS","steps":["macro_daily · 19:10 (+ KEY_RATE)","market_cap_daily · 19:10","commodity_daily · 08:00"],"tables":["macro","macro_data","stock_market_cap"],"api":["buffett"],"pages":["/buffett","/methodology/buffett"],"note":"auto-discover файла ВВП у Росстата хрупкий"},
 {"title":"Потоки капитала ЦБ и ОФЗ","src":"ОРФР Банка России (XLSX вручную), Минфин","steps":["CBR/fetch_orfr_flows · вручную по файлу"],"tables":["cbr_flows","ofz_auctions"],"api":["cbr_flows"],"pages":["/cbr-flows","/methodology/cbr-flows"],"note":"FX-вкладка заморожена"},
 {"title":"Крипта","src":"Bybit, Coinbase, mempool.space","steps":["Crypto/fetch_bybit_realtime · каждые 5 мин (cron)"],"tables":["crypto_candles","crypto_open_interest","btc_network_stats"],"api":[],"pages":[],"note":"ранняя стадия, на сайте не показывается"},
 {"title":"Международный ОИ","src":"CFTC, NSE, Eurex, TAIFEX, B3","steps":["IntlOI/* · вручную"],"tables":["open_interest_intl","candles_intl","price_breadth_intl_history"],"api":["oi_intl"],"pages":["только админ"],"note":"NSE/TAIFEX готовы, остальное частично; данные до 24.07"},
 {"title":"Сигналы, алерты, аномалии","src":"своя БД","steps":["signals/alerts_run · каждые 5 мин (cron)","anomaly_scan · ежечасно (cron)","frame-alert-bot · systemd","frame-tg-bot · контейнер"],"tables":["alerts","alert_fires","alert_events","anomalies","signal_log","telegram_link_tokens"],"api":["alerts","anomalies","events"],"pages":["/signal-export","/profile"],"note":"Telegram с сервера доступен только через релей"},
 {"title":"Второй мозг и завод постов","src":"Telegram-каналы, RSS и сайты, календарь MOEX, своя БД","steps":["news_web_scan · каждые 5 мин","tg_hype_scan · каждые 2 мин","channel_scan · каждые 5 мин","content_match · каждые 5 мин","content_ai · каждые 15 мин (⏸ выключен с 11.08)","data_release_scan · ежечасно","world_facts_build · вручную","мандаты MOEX · Routine еженедельно"],"tables":["news_archive","channel_posts","tg_channel_watch","content_candidates","content_feedback","world_facts","mandate_candidates","data_releases"],"api":["content_news","content_corpus","world_facts","mandate_scan"],"pages":["/admin/content-news"],"note":"следующий слой: карточки компаний (research/company_cards) и справочник эмитентов"},
 {"title":"Пользователи, биллинг, доступ","src":"T-Bank эквайринг, OAuth-провайдеры","steps":["backup_db · 03:00 (cron)","monitor_alert · каждые 15 мин (cron)"],"tables":["users","subscriptions","refresh_tokens","user_payment_methods","user_settings","api_keys","extension_tokens","analytics_events","ab_experiments","ab_assignments","trial_redemptions","subscription_invites","subscription_invite_redemptions","pipeline_runs"],"api":["auth","oauth","billing","api_keys","public_api","exports","extension","user_settings","analytics","csp_report","health_monitor","repaint"],"pages":["/login","/profile","/pricing","/billing/*","/admin/stats","/admin/users/:userId","/api-docs","/admin/repaint","/sandbox"],"note":"ЮKassa отключена, только T-Bank"},
]
cron=[("03:00 ежедневно","backup_db.sh → Telegram"),("04:00 вс","docker prune"),("04:30 1-го числа","cleanup_oi_5min.sh"),("06:30 пн","Funds/fetch_distributions.py"),("каждые 5 мин","signals/alerts_run.sh"),("15:00 UTC пн–пт","Funds/fetch_funds_realtime.py --once --force"),("каждые 15 мин","monitor_alert.sh"),("ежечасно :05","signals/anomaly_scan.sh"),("каждые 5 мин","signals/channel_scan.sh"),("12:00 1-го числа","signals/promo_push.sh"),("каждые 5 мин","signals/content_match.sh"),("каждые 2 мин","signals/tg_hype_scan.sh"),("каждые 15 мин","signals/content_ai.sh (⏸)"),("04:45 пн","nginx -t && reload"),("каждые 5 мин","Crypto/fetch_bybit_realtime.py"),("ежечасно :17","signals/data_release_scan.sh"),("каждые 5 мин","signals/news_web_scan.sh")]
containers=[("frame-api-N","FastAPI, gunicorn; имя растёт с деплоями"),("frame-orchestrator-1","main_orchestrator.py: 18 шагов, 5-мин цикл и дневной слот 19:10"),("frame-db-1","PostgreSQL 17, 17 ГБ"),("frame-redis-1","кэш чартов chart:*"),("frame-nginx-1","TLS, прокси, prerender"),("frame-tg-bot-1","бот подписок и алертов"),("frame-certbot-1","сертификаты"),("frame-alert-bot.service","host-side long-poll алертов"),("frame-content-review-bot.service","review-бот завода постов")]
research=[("moex_rebalance","ребаланс 18.09.2026: расчёт сделок фондов, валидация на 2025, xlsx биржи, посты"),("company_cards","разведка smart-lab: 223 бумаги, покрытие, план карточек компаний"),("content_pipeline_v2","эталон стиля, судья, бриф v2, второй мозг (MACRO_BRAIN)"),("moex_license","отчёт по информационному аудиту МосБиржи"),("forward","форвард-тест сессионных троек, заморожен до мая 2027"),("repo_shorts","репо в акциях: гипотезы и данные")]
skills=["moex-analytics","moex-backtest","moex-billing","moex-cbr-flows","moex-content-routines","moex-crypto","moex-data-triage","moex-db-query","moex-deploy-backend","moex-deploy-frontend","moex-fund-scha-backfill","moex-git-workflow","moex-local-dev-seed","moex-macro-refresh","moex-methodology-verify","moex-moex-ban","moex-new-indicator-scaffold","moex-publish-extension","moex-redesign","moex-responsive-audit","moex-seo","moex-server-access","moex-simplechart-usage","moex-timeweb-api"]
agents=["moex-deploy-verifier","moex-indicator-explorer","moex-methodology-auditor","moex-responsive-auditor","moex-timeweb-ops"]
data={"tables":tables,"routers":routers,"domains":DOM,"cron":cron,"containers":containers,"research":research,"skills":skills,"agents":agents,"today":str(today)}
tpl=(S/"map_template.html").read_text(encoding="utf-8")
html=tpl.replace("DATE",str(today).replace("-",".")).replace("DATA_JSON",json.dumps(data,ensure_ascii=False))
(S/"frame_map.html").write_text(html,encoding="utf-8"); print("готово:",len(html),"байт; таблиц",len(tables),"роутеров",len(routers),"эндпоинтов",sum(r["n"] for r in routers))
